[project]
name = "backend-public"
authors = []
description = ""
telemetry = false
requirements = []
costs_version = 2

[contracts.community-handles]
path = "contracts/community-handles.clar"
depends_on = []

[contracts.approving-namespace-owner]
path = "contracts/approving-namespace-owner.clar"
depends_on = []


[contracts.preordering-namespace-owner]
path = "contracts/preordering-namespace-owner.clar"
depends_on = []