[project]
name = "backend-public"
authors = []
description = ""
telemetry = false
requirements = []
costs_version = 2

[contracts.dao-names]
path = "contracts/dao-names.clar"
depends_on = []

[contracts.namespace-owner-2]
path = "contracts/namespace-owner-2.clar"
depends_on = []