[project]
name = "backend-public"
authors = []
description = ""
telemetry = false
requirements = []
costs_version = 2

[contracts.community-handles]
path = "contracts/community-handles.clar"
depends_on = []

[contracts.approving-namespace-controller]
path = "contracts/approving-namespace-controller.clar"
depends_on = []

[contracts.preordering-namespace-controller]
path = "contracts/preordering-namespace-controller.clar"
depends_on = []

[contracts.preordering-namespace-controller-2]
path = "contracts/preordering-namespace-controller.clar"
depends_on = []

[contracts.ryder-handles-controller]
path = "contracts/ryder-handles-controller.clar"
depends_on = []

[contracts.crypto]
path = "contracts/external/crypto.clar"
depends_on = []


[contracts.register-namespace]
path = "contracts/external/register-namespace.clar"
depends_on = []
